import turtle
turtle.speed(5)
turtle.pendown()
for i in range(4):
  turtle.forward(50)
  turtle.right(90)
turtle.right(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(15)
turtle.left(90)
turtle.forward(15)
turtle.right(90)
turtle.forward(20)
turtle.right(90)
turtle.forward(15)
turtle.right(90)
turtle.forward(35)
turtle.right(90)
turtle.forward(50)
turtle.right(45)
turtle.forward(35)
turtle.right(90)
turtle.forward(35)
